import { Plus_Jakarta_Sans } from "next/font/google";

import ReduxProvider from "@/redux/provider";
import ThemeProvider from "./theme-provider";

import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={plusJakartaSans.className}>
      <body className="bg-white dark:bg-gray-800">
        <ReduxProvider>
          <ThemeProvider>
            <main className="prose !max-w-full dark:prose-dark">
              {children}
            </main>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
